# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 22:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0001_initial'),
        ('collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='schemas',
            field=models.ManyToManyField(related_name='items', through='collection.Document', to='collection.Schema'),
        ),
        migrations.AddField(
            model_name='document',
            name='collections',
            field=models.ManyToManyField(related_name='documents', to='collection.Collection'),
        ),
        migrations.AddField(
            model_name='document',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='collection.Item'),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='collection.Schema'),
        ),
        migrations.AddField(
            model_name='collectionmembership',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_memberships', to='collection.Collection'),
        ),
        migrations.AddField(
            model_name='collectionmembership',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='collection.Document'),
        ),
        migrations.AddField(
            model_name='collectionmembership',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='collection.Item'),
        ),
        migrations.AddField(
            model_name='collectionmembership',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='collection.Schema'),
        ),
        migrations.AddField(
            model_name='collection',
            name='items',
            field=models.ManyToManyField(related_name='collections', through='collection.CollectionMembership', to='collection.Item'),
        ),
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='schemas',
            field=models.ManyToManyField(related_name='collections', through='collection.CollectionMembership', to='collection.Schema'),
        ),
        migrations.AddField(
            model_name='collection',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='workflow.Workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionmembership',
            unique_together=set([('item', 'collection')]),
        ),
    ]
