# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-05 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20171003_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='value',
            new_name='_value',
        ),
    ]
