# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-05 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20171005_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='_value',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
