# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-05 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20171005_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='_value',
            new_name='value',
        ),
    ]
