# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-05 17:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_auto_20171005_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
